Docs/gauge: стилизация
gazprom-neft/consta-charts pull request #17
Opened 2021-08-27 15:20 UTC by N1MBER

## Описание изменений

[Issue (#1453)](https://github.com/gazprom-neft/consta-uikit/issues/1453)

* Добавлена страничка для документации с примером кода, визуальным исполнением и минималбным описанием
* Сделан пример, отображающий вариант стилизации компонента, как в фигме

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-01 16:12 UTC, gizeasy requested changes

2021-09-01 16:12 UTC, gizeasy commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +  // eslint-disable-next-line
чего линтер отключил?

2021-09-01 16:16 UTC, gizeasy requested changes

2021-09-01 16:16 UTC, gizeasy commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +          stroke: '#C4C4C4',
Используй цвета из темы, если не совпадает цвет с макетом то вопрос к дизайнеру

2021-09-01 16:16 UTC, gizeasy commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +  const customFormatter = ({ percent }: { percent: number } | any): string => {
не используй any

2021-09-01 16:16 UTC, gizeasy commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +          color: 'var(color-base-essential)',
`color: 'var(color-base-essential)',`
кажется что это не работает

2021-09-01 16:20 UTC, gizeasy requested changes

2021-09-01 16:20 UTC, gizeasy commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +export const GaugeExample = () => {
Используй этот же пример в песочнице

2021-09-03 09:03 UTC, N1MBER commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +          stroke: '#C4C4C4',
Не нашел в теме этих цветов, поэтому использовал на прямую hex, заменить на близкий по оттенку из темы?

2021-09-03 10:12 UTC, N1MBER commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +          stroke: '#C4C4C4',
@kolebayev Какой цвет из фигмы взять?

2021-09-08 12:39 UTC, kolebayev commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +          stroke: '#C4C4C4',
color-bg-border

2021-09-08 13:59 UTC, N1MBER commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +  const customFormatter = ({ percent }: { percent: number } | any): string => {
Исправил, изменения в [этом комммите](https://github.com/gazprom-neft/consta-charts/commit/2285ebf187f0946a4fc05d56dd432c642a573ca1)

2021-09-08 13:59 UTC, N1MBER commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +export const GaugeExample = () => {
Исправил, изменения в [этом комммите](https://github.com/gazprom-neft/consta-charts/commit/2285ebf187f0946a4fc05d56dd432c642a573ca1)

2021-09-08 14:01 UTC, N1MBER commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +          color: 'var(color-base-essential)',
👍

2021-09-08 14:01 UTC, N1MBER commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +          stroke: '#C4C4C4',
👍

2021-09-08 14:01 UTC, N1MBER commented on src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
> +  // eslint-disable-next-line
👍

2021-09-09 11:09 UTC, gizeasy approved these changes

2021-09-09 11:11 UTC, merged