docs(Radar): стилизация
gazprom-neft/consta-charts pull request #18
Opened 2021-08-30 08:37 UTC by N1MBER

Add documentation page for Radar component with small description and example of use.

issue -  [#1451](https://github.com/gazprom-neft/consta-uikit/issues/1451)

## Описание изменений

* Добавлена страничка для документации компонента радара с примером кода, визуальным исполнением и минималбным описанием
* Сделан пример, отображающий вариант стилизации компонента, как в фигме

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-01 16:19 UTC, gizeasy requested changes

2021-09-01 16:19 UTC, gizeasy commented on src/Radar/__stories__/examples/RadarExample/RadarExample.tsx
> +export function RadarExample() {
Используй этот же пример в песочнице (вкладка Canvas)

2021-09-03 10:10 UTC, N1MBER commented on src/Radar/__stories__/examples/RadarExample/RadarExample.tsx
> +export function RadarExample() {
Изменения можно посмотреть в [этом коммите](https://github.com/gazprom-neft/consta-charts/tree/3c66bf68c9ab8e1683dfeeaac889c25055214fc4)

2021-09-09 11:07 UTC, gizeasy approved these changes

2021-09-09 11:08 UTC, merged