docs(Histogram): add documentation page for histogram
gazprom-neft/consta-charts pull request #19
Opened 2021-08-30 13:23 UTC by N1MBER

Add documentation page with small description and two examples of histogram (basic & stacked mode).

issue -  [#1452](https://github.com/gazprom-neft/consta-uikit/issues/1452)

## Описание изменений

* Добавлена страница для документации компонента гистограммы с примером кода, визуальным исполнением и минимальным описанием
* Сделаны два примера отображающие отображение гистограммой:  одной группы значений, нескольких групп значений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-09-01 16:23 UTC, gizeasy requested changes

2021-09-01 16:23 UTC, gizeasy commented on src/Histogram/__stories__/examples/HistogramExampleStacked/HistogramExampleStacked.tsx
> +    color: ['#04BC7F', '#33ACF2', '#FFA217'],
Посмотри есть ли эти цвета в теме, кажется что статусные цвета как раз сюда зайдут

2021-09-01 16:23 UTC, gizeasy commented on src/Histogram/__stories__/examples/HistogramExampleStacked/HistogramExampleStacked.tsx
> +export function HistogramExampleStacked() {
Используй этот же пример в песочнице

2021-09-01 16:23 UTC, gizeasy commented on src/Histogram/__stories__/examples/HistogramExampleStacked/HistogramExampleStacked.tsx
> +      renderer="svg"
`renderer="svg"` убери

2021-09-01 16:23 UTC, gizeasy commented on src/Histogram/__stories__/examples/HistogramExampleBasic/HistogramExampleBasic.tsx
> +      renderer="svg"
`renderer="svg"` убери

2021-09-03 10:07 UTC, N1MBER commented on src/Histogram/__stories__/examples/HistogramExampleStacked/HistogramExampleStacked.tsx
> +    color: ['#04BC7F', '#33ACF2', '#FFA217'],
Заменил на схожие цвета из темы, можно посмотреть в [этом же коммите (сквошил)](https://github.com/gazprom-neft/consta-charts/tree/3b2aa902b0026176eeada9bc2b499584e4ebd0c5)

2021-09-03 10:07 UTC, N1MBER commented on src/Histogram/__stories__/examples/HistogramExampleStacked/HistogramExampleStacked.tsx
> +export function HistogramExampleStacked() {
Изменения можно посмотреть в [этом же коммите](https://github.com/gazprom-neft/consta-charts/tree/3b2aa902b0026176eeada9bc2b499584e4ebd0c5)

2021-09-07 10:40 UTC, arhayka approved these changes

2021-09-09 11:06 UTC, gizeasy approved these changes

2021-09-09 11:06 UTC, merged